# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('create_time', models.DateField()),
                ('expire_time', models.DateField()),
                ('interest_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('wechat_id', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('permission', models.CharField(default='guest', max_length=20)),
                ('create_time', models.DateField()),
                ('last_login_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('departure_place', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('people_num', models.IntegerField()),
                ('price', models.IntegerField()),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseRent',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('community', models.CharField(max_length=40)),
                ('house_type', models.CharField(max_length=20)),
                ('rent', models.FloatField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('roommate_sex', models.CharField(max_length=6)),
                ('roommate_num', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MergeOrder',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('brand', models.CharField(max_length=30)),
                ('activity_type', models.CharField(max_length=30)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sublease',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('community', models.CharField(max_length=40)),
                ('house_type', models.CharField(max_length=20)),
                ('rent', models.FloatField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('renew', models.BooleanField(default=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('year', models.CharField(max_length=4)),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsedItem',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.Deal'),
        ),
        migrations.AddField(
            model_name='deal',
            name='posted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_user', to='webapps.User'),
        ),
        migrations.AddField(
            model_name='deal',
            name='saved_users',
            field=models.ManyToManyField(related_name='saved_by_users', to='webapps.User', verbose_name='user-saved deals'),
        ),
    ]
