# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapps.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_ch', models.CharField(max_length=40)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_ch', models.CharField(blank=True, max_length=60, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.CarBrand')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('create_time', models.DateField()),
                ('expire_time', models.DateField()),
                ('contact_type', models.CharField(default='1', max_length=20)),
                ('state', models.CharField(default='florida', max_length=30)),
                ('city', models.CharField(default='gainesville', max_length=30)),
                ('hot_index', models.FloatField(default=0)),
                ('title', models.CharField(default='deal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=webapps.utilities.upload_to_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat', models.CharField(default='None', max_length=30)),
                ('phone', models.CharField(default='1234567890', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('date', models.DateField()),
                ('time', models.TimeField(default='00:00:00')),
                ('depart_place', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('passenger_num', models.IntegerField()),
                ('price', models.FloatField()),
                ('car_type', models.CharField(default='sedan', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseRent',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('community', models.CharField(max_length=40)),
                ('bedroom_num', models.IntegerField(default=1)),
                ('bathroom_num', models.IntegerField(default=1)),
                ('rent', models.FloatField()),
                ('start_date', models.DateField()),
                ('duration', models.CharField(default='6 months', max_length=20)),
                ('roommate_gender', models.CharField(max_length=6)),
                ('roommate_num', models.IntegerField()),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MergeOrder',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('website', models.URLField(default='www.google.com', max_length=100)),
                ('order_type', models.CharField(max_length=30)),
                ('duedate', models.DateField(default='2017-12-31')),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sublease',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('community', models.CharField(max_length=40)),
                ('bedroom_num', models.IntegerField(default=1)),
                ('bathroom_num', models.IntegerField(default=1)),
                ('rent', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('renewal', models.BooleanField(default=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('note', models.TextField(null=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.CarBrand')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.CarModel')),
            ],
        ),
        migrations.CreateModel(
            name='UsedItem',
            fields=[
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapps.Deal')),
                ('item_type', models.CharField(default='electronic_default', max_length=20)),
                ('item_name', models.CharField(default='monitor_default', max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.Deal'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='posted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='saved_users',
            field=models.ManyToManyField(related_name='saved_by_users', to=settings.AUTH_USER_MODEL, verbose_name='users_deals'),
        ),
    ]
