# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0002_auto_20170406_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='interest_num',
        ),
        migrations.AddField(
            model_name='deal',
            name='city',
            field=models.CharField(default='gainesville', max_length=30),
        ),
        migrations.AddField(
            model_name='deal',
            name='state',
            field=models.CharField(default='florida', max_length=30),
        ),
    ]
