# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0002_carbrand_carmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sublease',
            old_name='renew',
            new_name='renewal',
        ),
        migrations.RemoveField(
            model_name='sublease',
            name='house_type',
        ),
        migrations.AddField(
            model_name='sublease',
            name='bathroom_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sublease',
            name='bedroom_num',
            field=models.IntegerField(default=1),
        ),
    ]
