# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0003_auto_20170411_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpool',
            name='price',
            field=models.FloatField(),
        ),
    ]
