# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0004_auto_20170411_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpool',
            old_name='people_num',
            new_name='passenger_num',
        ),
    ]
