# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0005_auto_20170411_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='saved_users',
            field=models.ManyToManyField(related_name='saved_by_users', to='webapps.User', verbose_name='users_deals'),
        ),
    ]
