# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0006_auto_20170412_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpool',
            name='datetime',
        ),
        migrations.AddField(
            model_name='carpool',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
