# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0007_auto_20170414_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpool',
            old_name='departure_place',
            new_name='depart_place',
        ),
        migrations.RenameField(
            model_name='houserent',
            old_name='roommate_sex',
            new_name='roommate_gender',
        ),
        migrations.RenameField(
            model_name='houserent',
            old_name='end_time',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='mergeorder',
            old_name='activity_type',
            new_name='order_type',
        ),
        migrations.RenameField(
            model_name='sublease',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='sublease',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='useditem',
            old_name='type',
            new_name='condition',
        ),
        migrations.RemoveField(
            model_name='carpool',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='carpool',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='houserent',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='mergeorder',
            name='brand',
        ),
        migrations.AddField(
            model_name='carpool',
            name='car_type',
            field=models.CharField(default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact_type',
            field=models.CharField(default='wechat', max_length=16),
        ),
        migrations.AddField(
            model_name='houserent',
            name='duration',
            field=models.CharField(default='6 months', max_length=20),
        ),
        migrations.AddField(
            model_name='mergeorder',
            name='duedate',
            field=models.DateField(default='2017-12-31'),
        ),
        migrations.AddField(
            model_name='mergeorder',
            name='website',
            field=models.URLField(default='www.google.com', max_length=100),
        ),
        migrations.AddField(
            model_name='useditem',
            name='item_name',
            field=models.CharField(default='monitor_default', max_length=20),
        ),
        migrations.AddField(
            model_name='useditem',
            name='item_type',
            field=models.CharField(default='electronic_default', max_length=20),
        ),
    ]
