# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0008_auto_20170414_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='user_1'),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_pw',
            field=models.CharField(default='admin', max_length=12),
        ),
        migrations.AlterField(
            model_name='carpool',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mergeorder',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sublease',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
