# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapps', '0009_auto_20170525_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat', models.CharField(default='None', max_length=30)),
                ('phone', models.IntegerField(default=1234567890)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default='99999999'),
        ),
        migrations.AddField(
            model_name='userpro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
