# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0010_auto_20170529_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='posted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='saved_users',
            field=models.ManyToManyField(related_name='saved_by_users', to=settings.AUTH_USER_MODEL, verbose_name='users_deals'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
