# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0011_auto_20170529_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
