# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0012_auto_20170529_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpool',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contact_type',
            field=models.CharField(default='email', max_length=16),
        ),
    ]
