# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0013_auto_20170530_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contact_type',
            field=models.CharField(default='email', max_length=30),
        ),
    ]
