# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0015_auto_20170603_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contact_type',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
