# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0016_auto_20170603_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapps.Deal'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='temp'),
        ),
    ]
