# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0017_auto_20170604_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.Deal'),
        ),
    ]
