# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0018_auto_20170604_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
    ]
