# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0019_remove_image_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='hot_index',
            field=models.FloatField(default=0),
        ),
    ]
