# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0020_deal_hot_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default='deal', max_length=50),
        ),
    ]
