# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 09:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webapps', '0021_deal_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_ch', models.CharField(max_length=40)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_ch', models.CharField(max_length=60)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.CarBrand')),
            ],
        ),
    ]
