# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webapps', '0022_carbrand_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name_ch',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
