# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 09:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import webapps.utilities


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapps', '0023_auto_20170614_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_seq',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to=webapps.utilities.upload_to_path),
        ),
    ]
