# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 15:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webapps', '0024_auto_20170615_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcar',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.CarBrand'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapps.CarModel'),
        ),
    ]
